name: CI (Unified Build, Test & Deploy)
on: {workflow_dispatch: null}
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests (pytest)
        env:
          DB_HOST: 127.0.0.1
          DB_USER: student
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: student_registration_db
          DB_PORT: '3306'
        run: |
          echo "pytest here"
      - name: Start container for integration tests
  run: |
    docker run -d --rm --name app \
      -p 5000:5000 -p 9100:9100 \
      -e DB_HOST=127.0.0.1 \
      -e DB_USER=student \
      -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
      -e DB_NAME=student_registration_db \
      -e DB_PORT=3306 \
      "${IMAGE_NAME_LOCAL}"
    echo "APP_BASE_URL=http://localhost:5000" >> "$GITHUB_ENV"
    echo "METRICS_URL=http://localhost:9100/metrics" >> "$GITHUB_ENV"
