name: CI

on:
  workflow_dispatch:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ci
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  lint-and-test:
    name: Lint and Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: backend/requirements*.txt

      - name: Install dependencies
        run: pip install -r backend/requirements.txt -r backend/requirements-ci.txt

      - name: Run linters
        run: make lint

      - name: Run unit tests
        env:
          DB_HOST: "localhost"
          DB_USER: "test"
          DB_PASSWORD: "test"
          DB_NAME: "test"
          DB_PORT: "3306"
        run: make unit-test

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            htmlcov/
            coverage.xml

  build-and-scan:
    name: Build and Scan Images
    runs-on: ubuntu-latest
    timeout-minutes: 25
    needs: [lint-and-test]
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: |
            student-app:ci
            student-frontend:ci
          load: true

      - name: Install Trivy
        run: |
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Run Trivy scan
        run: make scan

      - name: Save Docker images as artifact
        run: docker save -o images.tar student-app:ci student-frontend:ci

      - name: Upload Docker images artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: images.tar

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 35
    needs: [build-and-scan]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download and load Docker images
        uses: actions/download-artifact@v4
        with:
          name: docker-images
      - run: docker load -i images.tar

      - name: Prepare .env file
        env:
          DB_SECRET: ${{ secrets.DB_SECRET }}
        run: printf '%s\n' "$DB_SECRET" > infra/.env

      - name: Start services
        run: make up

      - name: Run integration tests
        run: make integration-test

      - name: Upload report artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-infra-report
          path: ci-report.html

      - name: Tear down services
        if: always()
        run: make down