name: CI

on:
  workflow_dispatch:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ci
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  lint_and_unit:
    name: Lint & Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r backend/requirements.txt -r backend/requirements-ci.txt

      - name: Lint
        run: make lint

      - name: Unit tests (no services)
        env:
          OTEL_SDK_DISABLED: "1"   # quiet OTEL exporter during unit runs
        run: make unit-test

      - name: Upload coverage (unit)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-unit
          path: |
            coverage.xml
            htmlcov

  integration:
    name: Integration / E2E
    needs: lint_and_unit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r backend/requirements.txt -r backend/requirements-ci.txt

      - name: Ensure helper scripts are executable
        run: chmod +x .github/scripts/wait-for-http.sh || true

      - name: Bring up stack
        run: |
          docker compose -f infra/docker-compose.yml -f infra/docker-compose.override.yml up -d --wait --wait-timeout 180

      - name: Wait for API health
        env:
          APP_BASE_URL: http://localhost:5000
        run: .github/scripts/wait-for-http.sh "${APP_BASE_URL}/health" 90

      - name: Run integration tests
        env:
          APP_BASE_URL: http://localhost:5000
          METRICS_URL: http://localhost:9100/metrics
        run: make integration-test

      - name: Tear down stack
        if: always()
        run: |
          docker compose -f infra/docker-compose.yml -f infra/docker-compose.override.yml down -v
