version: "3.9"
services:
  prometheus:
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9090/-/ready"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 15s

  otel-collector:
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:9464/metrics | head -n1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 15s

  app:
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_SERVICE_NAME=student-app
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 18
      start_period: 30s
